![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [5]:
print(my_array[8:6:-1])
print(my_array[-2:-4:-1])

[8 7]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [6]:
print(my_array[2::-1])

[2 1 0]


In [8]:
print(np.array(sorted(my_array[:3], reverse= True)))

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [9]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [10]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [11]:
print(my_matrix[::-1, ::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [12]:
print(my_matrix.T)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [13]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [14]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [15]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
print(my_matrix[::2, ::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [17]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
print(my_matrix[:3, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [19]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x)

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']


In [20]:
print(x == "Loro")

[ True False False  True False]


In [21]:
print(x[x == "Loro"])

['Loro' 'Loro']


In [22]:
print(x[np.where(x=="Loro")])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [26]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [27]:
print(x.ndim)

3


In [28]:
print(x.shape)

(2, 5, 2)


In [29]:
print(x.size)

20


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [30]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
print(x.nbytes)
print(x.itemsize)

80
8


In [35]:
print(x.dtype)

float64


In [36]:
x = np.full((10,),0)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
print(x.dtype)

int64


In [38]:
print(x.nbytes)

80


In [33]:
x[3] = 1

In [34]:
print(x)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [39]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [40]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [41]:
ejer_12 = np.array([1,2,0,0,4,0])
print(ejer_12)

[1 2 0 0 4 0]


In [47]:
print(*ejer_12[np.where(ejer_12 != 0)])

1 2 4


In [61]:
def f_ejer_12(vector_12):
    return np.where(vector_12 != 0)[0]

In [55]:
ejer_12 = np.array([1,2,0,0,4,0])
resultado = f_ejer_12(ejer_12)

In [64]:
resultado_12 = f_ejer_12(ejer_12)
print(resultado_12)


[0 1 4]


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [ ]:
x = np.random.randint(100, size = (10,10))
print(x)

print("Minimo: ", np.min(x))
print("Maximo: ", np.max(x))
print("MINIMO 2: ", x.min())
print("MAXIMO 2:", x.max()) 

min = np.min(x)

[[83  8 19 94 32 66 47 43 89 13]
 [66 64 70 52 64 92 49 32 75 97]
 [60  0 61 33  0 88 99 88 99 61]
 [96 51 70 93 35 30 71 64 13 60]
 [55 30 45 36 92 46 25 86 12 83]
 [67 91 58 37 67 51 65 37 64 16]
 [99 96 94 52 79 27 61 84 67 77]
 [90 52 47 18 25 15 52 81 33 42]
 [ 0 82 60 87 81 26  3 21 79  1]
 [76 21 82 75 23 58 16 54 61 58]]
Minimo:  0
Maximo:  99
MINIMO 2:  0
MAXIMO 2: 99


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [67]:
x = np.random.random(30)
print(x)

[0.7572585  0.95912976 0.5090993  0.12246775 0.29486648 0.37075041
 0.88669022 0.43912292 0.97965892 0.54315143 0.08124627 0.62258035
 0.92053227 0.87971666 0.4675188  0.73779659 0.33488406 0.5387691
 0.98151451 0.0824996  0.54616582 0.90987767 0.88700763 0.45316962
 0.28965863 0.18693278 0.87380918 0.29794139 0.76450489 0.97613557]


In [71]:
print(np.mean(x))
print(x.mean())
print(x.sum()/len(x))

0.5898152361188518
0.5898152361188518
0.5898152361188518


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [76]:
ejer_15 = np.ones((10,10))
print(ejer_15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [77]:
ejer_15[1:-1,1:-1] = 0
print(ejer_15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [82]:
x = np.zeros((8,8))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
x[::2,1::2] = 1
x[1::2, ::2]  = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [88]:
ejer_17 = np.array([[0,1],[1,0]])
print(ejer_17)

[[0 1]
 [1 0]]


In [92]:
x = np.tile(ejer_17, (4,4)) 
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [93]:
x = np.random.randint(1,20, (5,5))
print(x)

[[16 12 16 11 16]
 [ 2  8  4 10  2]
 [17 19  2  8  1]
 [14  9  4 15 17]
 [18  9 11 11 10]]


In [94]:
(x - np.mean(x)/np.std(x))

array([[14.08437354, 10.08437354, 14.08437354,  9.08437354, 14.08437354],
       [ 0.08437354,  6.08437354,  2.08437354,  8.08437354,  0.08437354],
       [15.08437354, 17.08437354,  0.08437354,  6.08437354, -0.91562646],
       [12.08437354,  7.08437354,  2.08437354, 13.08437354, 15.08437354],
       [16.08437354,  7.08437354,  9.08437354,  9.08437354,  8.08437354]])

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [113]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [96]:
y = x.copy()

y[(y>= 3) & (y <=8)] = -1
print(y)


[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [116]:
y_2 = x.copy()

y_2[(y_2>= 3) & (y_2 <=8)] *= -1
print(y_2)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
